# This file establishes example/ as its own workspace root so that pnpm treats
# it as an independent project. Without this, the parent directory's
# pnpm-workspace.yaml causes pnpm to skip installing example's dependencies
# (even with `packages: []` in the parent). This is a known pnpm limitation:
# https://github.com/pnpm/pnpm/issues/2412
packages: []
