auditConfig:
  ignoreCves:
    # Ignore CVE-2026-26996 (minimatch ReDoS): eslint 9.x and typescript-eslint
    # 8.x depend on minimatch 3.x/9.x which have no patched release. eslint 10
    # fixes this but isn't supported by the plugin ecosystem yet. Remove this
    # ignore once upstream updates land.
    - CVE-2026-26996
